# -*- coding: utf-8 -*-
"""ResoluteAI_Task-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Cl5iHNXnKfbWTCcmFmHKlMv6TeuFQLe
"""

!pip install PyMuPDF transformers torch bert-extractive-summarizer

import fitz  # PyMuPDF
from summarizer import Summarizer

def read_pdf(file_path):
    """Read the content of a PDF file using PyMuPDF."""
    text = ""
    with fitz.open(file_path) as doc:
        for page in doc:
            text += page.get_text()
    return text

def summarize_text(text):
    """Summarize the text using BERT extractive summarizer."""
    model = Summarizer()
    summary = model(text, min_length=60, max_length=500)
    return summary

def main():
    pdf_path = "Operations Management.pdf"  # Ensure this file is in your Colab directory
    text = read_pdf(pdf_path)

    # Summarize the content
    summary = summarize_text(text)
    print("Summary:")
    print(summary)

if __name__ == "__main__":
    main()

